// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "ImportProps.h"
#include "PaintView.h"

inline void CImportProps::cb_btnOk_i(Fl_HoverButton*, void*) {
  m_modalResult = MR_OK;
wndImportProps->hide();
}
void CImportProps::cb_btnOk(Fl_HoverButton* o, void* v) {
  ((CImportProps*)(o->parent()->user_data()))->cb_btnOk_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *idata_additional[] = {
"     5    36       18            1",
"` c #656565",
". c #696969",
"# c #797975",
"a c #797979",
"b c #7d7d7d",
"c c #81817d",
"d c #898989",
"e c #959191",
"f c #a19d9d",
"g c #aeaeaa",
"h c #b2aeaa",
"i c #bab6b2",
"j c #c6c6c2",
"k c #cecec6",
"l c #cececa",
"m c #d2ceca",
"n c #d2d2ca",
"o c None",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"olooo",
"lfmoo",
"lbioo",
"l#dmo",
"l#.ho",
"l#`ck",
"l#``h",
"l#``h",
"l#`ck",
"l#`go",
"l#cko",
"lagoo",
"lekoo",
"njooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo"
};
static Fl_Pixmap image_additional(idata_additional);

inline void CImportProps::cb_rbImportNewModel_i(Fl_Round_Button*, void*) {
  CPaintView* paintView = (CPaintView*)m_view;
paintView->setImportMode(CPaintView::IM_NEW_MODEL);
}
void CImportProps::cb_rbImportNewModel(Fl_Round_Button* o, void* v) {
  ((CImportProps*)(o->parent()->user_data()))->cb_rbImportNewModel_i(o,v);
}

inline void CImportProps::cb_rbImportAndPaste_i(Fl_Round_Button*, void*) {
  CPaintView* paintView = (CPaintView*)m_view;
paintView->setImportMode(CPaintView::IM_PASTE);
}
void CImportProps::cb_rbImportAndPaste(Fl_Round_Button* o, void* v) {
  ((CImportProps*)(o->parent()->user_data()))->cb_rbImportAndPaste_i(o,v);
}

CImportProps::CImportProps() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = wndImportProps = new Fl_Double_Window(184, 73, "Drawing properties");
    w = o;
    o->box(FL_THIN_UP_BOX);
    o->user_data((void*)(this));
    { Fl_HoverButton* o = btnOk = new Fl_HoverButton(1, 1, 9, 42);
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->image(image_additional);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(12);
      o->labelcolor(FL_BLACK);
      o->callback((Fl_Callback*)cb_btnOk);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    { Fl_Round_Button* o = rbImportNewModel = new Fl_Round_Button(15, 4, 135, 18, "Import as new model");
      o->type(102);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->value(1);
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_rbImportNewModel);
    }
    { Fl_Round_Button* o = rbImportAndPaste = new Fl_Round_Button(15, 22, 135, 18, "Import and paste");
      o->type(102);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_rbImportAndPaste);
    }
    o->set_non_modal();
    o->clear_border();
    o->end();
  }
}

CImportProps::~CImportProps() {
  delete wndImportProps;
}

void CImportProps::show() {
  setSize(wndImportProps->w(),btnOk->h()+2);

if (m_view!=NULL)
{
	CPaintView* paintView = (CPaintView*) m_view;
	
	if (paintView->getImportMode()==CPaintView::IM_NEW_MODEL)
		rbImportNewModel->value(1);
	else
		rbImportAndPaste->value(1);
}

wndImportProps->show();
}

void CImportProps::setPosition(int x, int y) {
  wndImportProps->position(x, y);
}

void CImportProps::setSize(int width, int height) {
  wndImportProps->size_range(0, 0);
wndImportProps->size(width, height);
}

void CImportProps::setView(void* p) {
  m_view = p;
}

void CImportProps::hide() {
  wndImportProps->hide();
}
