// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "LogWindow.h"
#include <iostream>
CLogWindow* CLogWindow::m_instance = 0; 

CLogWindow::CLogWindow() {
}

void CLogWindow::hide() {
}

void CLogWindow::show() {
}

CLogWindow* CLogWindow::getInstance() {
  if(m_instance==0)
{
	m_instance = new CLogWindow();
        return m_instance;
}
else
{
	return m_instance;
}
}

void CLogWindow::print(const char* txt) {
  using namespace std;
cout << txt << endl;
}

void CLogWindow::print(const char* context, const char* txt) {
  using namespace std;
cout << context << ": " << txt << endl;
}
