#!/usr/bin/python

import os, sys, string, shutil

def checkBuildDir():

	buildDir = "../forcepad_build_"+sys.platform

	if os.path.exists(buildDir):
		print "Build directory exists. Removing..."
		shutil.rmtree(buildDir)

	os.mkdir(buildDir)
	
	return buildDir
	
def runCMake(buildDir, fltkDir, glewDir):
	
	cmdOptions = "-D FLTK_ROOT:FILEPATH=%s " % fltkDir
	cmdOptions += "-D GLEW_ROOT:FILEPATH=%s " % glewDir
	cmdOptions += '-G "Eclipse CDT4 - Unix Makefiles"'
	
	oldDir = os.getcwd()
	
	os.chdir(buildDir)
	
	os.system('cmake '+cmdOptions+' ../forcepad')
	
	os.chdir(oldDir)
	

if __name__ == "__main__":
	
	fltkDir = "/Users/jonas/Documents/Libraries/fltk-1.3"
	glewDir = "/Users/jonas/Documents/Libraries/glew"
	
	buildDir = checkBuildDir()
	runCMake(buildDir, fltkDir, glewDir)
