// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef CalcSettings_h
#define CalcSettings_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>

class CCalcSettings {
  void* m_paintView; 
public:
  CCalcSettings();
  Fl_Double_Window *mainWindow;
  Fl_Group *meshGroup;
  Fl_Value_Slider *gridStep;
  Fl_Group *generalGroup;
  Fl_Value_Input *elasticModulus;
  Fl_Value_Input *stiffnessScaleFactor;
  Fl_Value_Input *youngsModulus;
  Fl_Value_Input *thickness;
  Fl_Value_Input *elementTreshold;
  Fl_Group *constraintGroup;
  Fl_Value_Input *constraintStiffnessScaleFactor;
  Fl_Value_Input *forceMagnitude;
  Fl_Value_Input *weight;
  Fl_Button *cancelButton;
private:
  inline void cb_cancelButton_i(Fl_Button*, void*);
  static void cb_cancelButton(Fl_Button*, void*);
public:
  Fl_Button *okButton;
private:
  inline void cb_okButton_i(Fl_Button*, void*);
  static void cb_okButton(Fl_Button*, void*);
public:
  void show();
  void setView(void* view);
  void setData();
  void getData();
  void centerWindow(Fl_Window* window);
};
#endif
