// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef GeneralSettings_h
#define GeneralSettings_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Slider.H>

class CGeneralSettings {
  void* m_paintView; 
public:
  CGeneralSettings();
  Fl_Double_Window *mainWindow;
  Fl_Button *okButton;
private:
  void cb_okButton_i(Fl_Button*, void*);
  static void cb_okButton(Fl_Button*, void*);
public:
  Fl_Value_Slider *lineThickness;
private:
  void cb_lineThickness_i(Fl_Value_Slider*, void*);
  static void cb_lineThickness(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *symbolLength;
private:
  void cb_symbolLength_i(Fl_Value_Slider*, void*);
  static void cb_symbolLength(Fl_Value_Slider*, void*);
public:
  void show();
  void setView(void* view);
  void setData();
  void getData();
  void centerWindow(Fl_Window* window);
};
#endif
