// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef TabletToolbar_h
#define TabletToolbar_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class CTabletToolbar {
  void* m_paintView; 
public:
  CTabletToolbar();
  Fl_Double_Window *mainWindow;
  Fl_Button *btnOpen;
private:
  void cb_btnOpen_i(Fl_Button*, void*);
  static void cb_btnOpen(Fl_Button*, void*);
public:
  Fl_Button *btnNew;
private:
  void cb_btnNew_i(Fl_Button*, void*);
  static void cb_btnNew(Fl_Button*, void*);
public:
  Fl_Button *btnSaveAs;
private:
  void cb_btnSaveAs_i(Fl_Button*, void*);
  static void cb_btnSaveAs(Fl_Button*, void*);
public:
  Fl_Button *btnUndo;
private:
  void cb_btnUndo_i(Fl_Button*, void*);
  static void cb_btnUndo(Fl_Button*, void*);
public:
  Fl_Button *btnSettings;
  void show();
  void setView(void* view);
  void centerWindow(Fl_Window* window);
};
#endif
