// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef VizMixerToolbar_h
#define VizMixerToolbar_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Fl_HoverButton.h"
#include <FL/Fl_Group.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Box.H>

class CVizMixerToolbar {
  void* m_paintView; 
public:
  CVizMixerToolbar();
  Fl_Double_Window *mainWindow;
  Fl_HoverButton *btnStress;
  Fl_HoverButton *btnDisplacements;
  Fl_HoverButton *btnMisesStress;
  Fl_HoverButton *btnTensionCompression;
private:
  void cb_btnTensionCompression_i(Fl_HoverButton*, void*);
  static void cb_btnTensionCompression(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnTension;
private:
  void cb_btnTension_i(Fl_HoverButton*, void*);
  static void cb_btnTension(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnCompression;
private:
  void cb_btnCompression_i(Fl_HoverButton*, void*);
  static void cb_btnCompression(Fl_HoverButton*, void*);
public:
  Fl_Roller *rolArrowSize;
private:
  void cb_rolArrowSize_i(Fl_Roller*, void*);
  static void cb_rolArrowSize(Fl_Roller*, void*);
public:
  Fl_Roller *rolTransparency;
private:
  void cb_rolTransparency_i(Fl_Roller*, void*);
  static void cb_rolTransparency(Fl_Roller*, void*);
public:
  Fl_Roller *rolStep;
private:
  void cb_rolStep_i(Fl_Roller*, void*);
  static void cb_rolStep(Fl_Roller*, void*);
public:
  Fl_HoverButton *btnLockScale;
private:
  void cb_btnLockScale_i(Fl_HoverButton*, void*);
  static void cb_btnLockScale(Fl_HoverButton*, void*);
public:
  Fl_Slider *minStress;
private:
  void cb_minStress_i(Fl_Slider*, void*);
  static void cb_minStress(Fl_Slider*, void*);
public:
  Fl_Slider *maxStress;
private:
  void cb_maxStress_i(Fl_Slider*, void*);
  static void cb_maxStress(Fl_Slider*, void*);
public:
  Fl_Roller *maxIntensity;
private:
  void cb_maxIntensity_i(Fl_Roller*, void*);
  static void cb_maxIntensity(Fl_Roller*, void*);
public:
  Fl_Roller *stressWidth;
private:
  void cb_stressWidth_i(Fl_Roller*, void*);
  static void cb_stressWidth(Fl_Roller*, void*);
public:
  void show();
  void setView(void* view);
  void centerWindow(Fl_Window* window);
  void placeWindow(Fl_Window* window);
  void hide();
};
#endif
