// generated by Fast Light User Interface Designer (fluid) version 1.0101

#include "StatusDlg.h"

CStatusDlg::CStatusDlg() {
  Fl_Window* w;
  { Fl_Window* o = wndStatus = new Fl_Window(309, 100, "Calculating...");
    w = o;
    o->user_data((void*)(this));
    { Fl_Value_Slider* o = sldProgress = new Fl_Value_Slider(4, 66, 302, 28);
      o->type(3);
      o->box(FL_PLASTIC_DOWN_BOX);
      o->maximum(99);
      o->step(1);
    }
    { Fl_Output* o = outStatus = new Fl_Output(4, 6, 301, 54);
      o->box(FL_PLASTIC_DOWN_BOX);
    }
    o->set_modal();
    o->end();
  }
}

CStatusDlg::~CStatusDlg() {
  delete wndStatus;
}

void CStatusDlg::show() {
  wndStatus->show();
}

void CStatusDlg::setStatusText(const char* text) {
  outStatus->value(text);
this->refresh();
}

void CStatusDlg::setProgress(int percent) {
  sldProgress->value(percent);
this->refresh();
}

void CStatusDlg::hide() {
  wndStatus->hide();
}

void CStatusDlg::refresh() {
  Fl::check();
Fl::flush();
}
