// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef ImportProps_h
#define ImportProps_h
#include <FL/Fl.H>
#define MR_OK 0
#define MR_CANCEL 1
#include <FL/Fl_Double_Window.H>
#include "Fl_HoverButton.h"
#include <FL/Fl_Round_Button.H>

class CImportProps {
  void* m_view;
  int m_modalResult;
public:
  CImportProps();
  Fl_Double_Window *wndImportProps;
  Fl_HoverButton *btnOk;
private:
  inline void cb_btnOk_i(Fl_HoverButton*, void*);
  static void cb_btnOk(Fl_HoverButton*, void*);
public:
  Fl_Round_Button *rbImportNewModel;
private:
  inline void cb_rbImportNewModel_i(Fl_Round_Button*, void*);
  static void cb_rbImportNewModel(Fl_Round_Button*, void*);
public:
  Fl_Round_Button *rbImportAndPaste;
private:
  inline void cb_rbImportAndPaste_i(Fl_Round_Button*, void*);
  static void cb_rbImportAndPaste(Fl_Round_Button*, void*);
public:
  ~CImportProps();
  void show();
  void setPosition(int x, int y);
  void setSize(int width, int height);
  void setView(void* p);
  void hide();
};
#endif
