// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "GeneralSettings.h"
#include "PaintView.h"

void CGeneralSettings::cb_okButton_i(Fl_Button*, void*) {
  mainWindow->hide();
}
void CGeneralSettings::cb_okButton(Fl_Button* o, void* v) {
  ((CGeneralSettings*)(o->parent()->user_data()))->cb_okButton_i(o,v);
}

void CGeneralSettings::cb_lineThickness_i(Fl_Value_Slider*, void*) {
  CPaintView* view = (CPaintView*)m_paintView;
view->setUiLineThickness(lineThickness->value());
}
void CGeneralSettings::cb_lineThickness(Fl_Value_Slider* o, void* v) {
  ((CGeneralSettings*)(o->parent()->user_data()))->cb_lineThickness_i(o,v);
}

void CGeneralSettings::cb_symbolLength_i(Fl_Value_Slider*, void*) {
  CPaintView* view = (CPaintView*)m_paintView;
view->setUiSymbolLength(symbolLength->value());
}
void CGeneralSettings::cb_symbolLength(Fl_Value_Slider* o, void* v) {
  ((CGeneralSettings*)(o->parent()->user_data()))->cb_symbolLength_i(o,v);
}

CGeneralSettings::CGeneralSettings() {
  { mainWindow = new Fl_Double_Window(318, 140, "General Settings");
    mainWindow->user_data((void*)(this));
    { okButton = new Fl_Button(230, 100, 70, 25, "Close");
      okButton->labelsize(11);
      okButton->callback((Fl_Callback*)cb_okButton);
    } // Fl_Button* okButton
    { lineThickness = new Fl_Value_Slider(14, 25, 286, 20, "Line thickness (pixels)");
      lineThickness->type(5);
      lineThickness->labelsize(11);
      lineThickness->minimum(1);
      lineThickness->maximum(20);
      lineThickness->step(1);
      lineThickness->value(2);
      lineThickness->textsize(11);
      lineThickness->callback((Fl_Callback*)cb_lineThickness);
      lineThickness->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Value_Slider* lineThickness
    { symbolLength = new Fl_Value_Slider(14, 65, 286, 20, "Symbol length (pixels)");
      symbolLength->type(5);
      symbolLength->labelsize(11);
      symbolLength->minimum(10);
      symbolLength->maximum(300);
      symbolLength->step(5);
      symbolLength->value(50);
      symbolLength->textsize(11);
      symbolLength->callback((Fl_Callback*)cb_symbolLength);
      symbolLength->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Value_Slider* symbolLength
    mainWindow->set_modal();
    mainWindow->end();
  } // Fl_Double_Window* mainWindow
  m_paintView = NULL;
}

void CGeneralSettings::show() {
  this->setData();
mainWindow->show();
while (mainWindow->visible()) Fl::wait();
}

void CGeneralSettings::setView(void* view) {
  m_paintView = (CPaintView*)view;
}

void CGeneralSettings::setData() {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	
	lineThickness->value(view->getUiLineThickness());
	symbolLength->value(view->getUiSymbolLength());
}
}

void CGeneralSettings::getData() {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;	
}
}

void CGeneralSettings::centerWindow(Fl_Window* window) {
  mainWindow->position(window->x()+window->w()/2-mainWindow->w()/2, window->y()+window->h()/2-mainWindow->h()/2);
}
