// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef TabletToolbar_h
#define TabletToolbar_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Fl_HoverButton.h"
#include "FlPaintView.h"

class CTabletToolbar {
  void* m_paintView; 
public:
  CTabletToolbar();
  Fl_Double_Window *mainWindow;
  Fl_HoverButton *btnOpen;
private:
  inline void cb_btnOpen_i(Fl_HoverButton*, void*);
  static void cb_btnOpen(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnNew;
private:
  inline void cb_btnNew_i(Fl_HoverButton*, void*);
  static void cb_btnNew(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnSaveAs;
private:
  inline void cb_btnSaveAs_i(Fl_HoverButton*, void*);
  static void cb_btnSaveAs(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnUndo;
private:
  inline void cb_btnUndo_i(Fl_HoverButton*, void*);
  static void cb_btnUndo(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnSettings;
private:
  inline void cb_btnSettings_i(Fl_HoverButton*, void*);
  static void cb_btnSettings(Fl_HoverButton*, void*);
public:
  void show();
  void setView(void* view);
  void centerWindow(Fl_Window* window);
  void placeWindow(Fl_Window* window);
  void hide();
};
#endif
