// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "TabletToolbar_kiosk.h"
#include "PaintView.h"
#include "CalcSettings.h"
#include "PlatformInfo.h"
#ifdef WIN32
#include "resource.h"
#include "dwmapi.h"
#endif
#ifndef __APPLE__
#include <FL/x.H>
#endif

void CTabletToolbar::cb_btnNew_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->newModel();
};
}
void CTabletToolbar::cb_btnNew(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnNew_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *idata_new_model_black[] = {
"    36    36      256            2",
"`` c None",
"`. c #030303",
"`# c #979797",
"`a c #bfbfbf",
"`b c #2f2f2f",
"`c c #ffffff",
"`d c #fdfdfd",
"`e c #535353",
"`f c #e7e7e7",
"`g c #f3f3f3",
"`h c #fbfbfb",
"`i c #9f9f9f",
"`j c #c9c9c9",
"`k c #6f6f6f",
"`l c #dbdbdb",
"`m c #232323",
"`n c #a7a7a7",
"`o c #777777",
"`p c #0b0b0b",
"`q c #b7b7b7",
"`r c #dfdfdf",
"`s c #f8f8f8",
"`t c #efefef",
"`u c #878787",
"`v c #070707",
"`w c #000000",
"`x c #000000",
"`y c #000000",
"`z c #000000",
"`A c #000000",
"`B c #000000",
"`C c #000000",
"`D c #000000",
"`E c #000000",
"`F c #000000",
"`G c #000000",
"`H c #000000",
"`I c #000000",
"`J c #000000",
"`K c #000000",
"`L c #000000",
"`M c #000000",
"`N c #000000",
"`O c #000000",
"`P c #000000",
"`Q c #000000",
"`R c #000000",
"`S c #000000",
"`T c #000000",
"`U c #000000",
"`V c #000000",
"`W c #000000",
"`X c #000000",
"`Y c #000000",
"`Z c #000000",
"`0 c #000000",
"`1 c #000000",
"`2 c #000000",
"`3 c #000000",
"`4 c #000000",
"`5 c #000000",
"`6 c #000000",
"`7 c #000000",
"`8 c #000000",
".` c #000000",
".. c #000000",
".# c #000000",
".a c #000000",
".b c #000000",
".c c #000000",
".d c #000000",
".e c #000000",
".f c #000000",
".g c #000000",
".h c #000000",
".i c #000000",
".j c #000000",
".k c #000000",
".l c #000000",
".m c #000000",
".n c #000000",
".o c #000000",
".p c #000000",
".q c #000000",
".r c #000000",
".s c #000000",
".t c #000000",
".u c #000000",
".v c #000000",
".w c #000000",
".x c #000000",
".y c #000000",
".z c #000000",
".A c #000000",
".B c #000000",
".C c #000000",
".D c #000000",
".E c #000000",
".F c #000000",
".G c #000000",
".H c #000000",
".I c #000000",
".J c #000000",
".K c #000000",
".L c #000000",
".M c #000000",
".N c #000000",
".O c #000000",
".P c #000000",
".Q c #000000",
".R c #000000",
".S c #000000",
".T c #000000",
".U c #000000",
".V c #000000",
".W c #000000",
".X c #000000",
".Y c #000000",
".Z c #000000",
".0 c #000000",
".1 c #000000",
".2 c #000000",
".3 c #000000",
".4 c #000000",
".5 c #000000",
".6 c #000000",
".7 c #000000",
".8 c #000000",
"#` c #000000",
"#. c #000000",
"## c #000000",
"#a c #000000",
"#b c #000000",
"#c c #000000",
"#d c #000000",
"#e c #000000",
"#f c #000000",
"#g c #000000",
"#h c #000000",
"#i c #000000",
"#j c #000000",
"#k c #000000",
"#l c #000000",
"#m c #000000",
"#n c #000000",
"#o c #000000",
"#p c #000000",
"#q c #000000",
"#r c #000000",
"#s c #000000",
"#t c #000000",
"#u c #000000",
"#v c #000000",
"#w c #000000",
"#x c #000000",
"#y c #000000",
"#z c #000000",
"#A c #000000",
"#B c #000000",
"#C c #000000",
"#D c #000000",
"#E c #000000",
"#F c #000000",
"#G c #000000",
"#H c #000000",
"#I c #000000",
"#J c #000000",
"#K c #000000",
"#L c #000000",
"#M c #000000",
"#N c #000000",
"#O c #000000",
"#P c #000000",
"#Q c #000000",
"#R c #000000",
"#S c #000000",
"#T c #000000",
"#U c #000000",
"#V c #000000",
"#W c #000000",
"#X c #000000",
"#Y c #000000",
"#Z c #000000",
"#0 c #000000",
"#1 c #000000",
"#2 c #000000",
"#3 c #000000",
"#4 c #000000",
"#5 c #000000",
"#6 c #000000",
"#7 c #000000",
"#8 c #000000",
"a` c #000000",
"a. c #000000",
"a# c #000000",
"aa c #000000",
"ab c #000000",
"ac c #000000",
"ad c #000000",
"ae c #000000",
"af c #000000",
"ag c #000000",
"ah c #000000",
"ai c #000000",
"aj c #000000",
"ak c #000000",
"al c #000000",
"am c #000000",
"an c #000000",
"ao c #000000",
"ap c #000000",
"aq c #000000",
"ar c #000000",
"as c #000000",
"at c #000000",
"au c #000000",
"av c #000000",
"aw c #000000",
"ax c #000000",
"ay c #000000",
"az c #000000",
"aA c #000000",
"aB c #000000",
"aC c #000000",
"aD c #000000",
"aE c #000000",
"aF c #000000",
"aG c #000000",
"aH c #000000",
"aI c #000000",
"aJ c #000000",
"aK c #000000",
"aL c #000000",
"aM c #000000",
"aN c #000000",
"aO c #000000",
"aP c #000000",
"aQ c #000000",
"aR c #000000",
"aS c #000000",
"aT c #000000",
"aU c #000000",
"aV c #000000",
"aW c #000000",
"aX c #000000",
"aY c #000000",
"aZ c #000000",
"a0 c #000000",
"a1 c #000000",
"a2 c #000000",
"a3 c #000000",
"a4 c #000000",
"a5 c #000000",
"a6 c #000000",
"a7 c #000000",
"a8 c #000000",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"```````````````.`#`a`a`a`a`a`a`a`a`a`a`a`#`b````````````````````````````",
"```````````````#`c`c`c`c`c`c`c`c`c`c`c`c`c`d`e``````````````````````````",
"```````````````a`c`f`a`a`a`a`a`a`a`a`a`g`c`c`h`e````````````````````````",
"```````````````a`c`i```````````````````a`c`c`c`h`e``````````````````````",
"```````````````a`c`i```````````````````a`c`j`c`c`h`e````````````````````",
"```````````````a`c`i```````````````````a`c`i`k`c`c`h`e``````````````````",
"```````````````a`c`i```````````````````a`c`i```k`c`c`h`e````````````````",
"```````````````a`c`i```````````````````a`c`i`````k`c`c`h`e``````````````",
"```````````````a`c`i```````````````````a`c`f`a`a`a`l`c`c`d`m````````````",
"```````````````a`c`i```````````````````n`c`c`c`c`c`c`c`c`c`o````````````",
"```````````````a`c`i```````````````````p`q`r`r`r`r`r`r`s`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`i```````````````````````````````````a`c`i````````````",
"```````````````a`c`f`a`a`a`a`a`a`a`a`a`a`a`a`a`a`a`a`a`t`c`i````````````",
"```````````````n`c`c`c`c`c`c`c`c`c`c`c`c`c`c`c`c`c`c`c`c`c`u````````````",
"```````````````v`#`a`a`a`a`a`a`a`a`a`a`a`a`a`a`a`a`a`a`a`#`.````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````"
};
static Fl_Pixmap image_new_model_black(idata_new_model_black);

void CTabletToolbar::cb_btnUndo_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->undo();
};
}
void CTabletToolbar::cb_btnUndo(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnUndo_i(o,v);
}

static const char *idata_undo_black[] = {
"    36    36      256            2",
"`` c None",
"`. c #1b1b1b",
"`# c #7b7b7b",
"`a c #c3c3c3",
"`b c #dfdfdf",
"`c c #f3f3f3",
"`d c #bbbbbb",
"`e c #5f5f5f",
"`f c #030303",
"`g c #171717",
"`h c #9b9b9b",
"`i c #fbfbfb",
"`j c #ffffff",
"`k c #d3d3d3",
"`l c #232323",
"`m c #3f3f3f",
"`n c #676767",
"`o c #efefef",
"`p c #dbdbdb",
"`q c #b7b7b7",
"`r c #9f9f9f",
"`s c #e7e7e7",
"`t c #ebebeb",
"`u c #373737",
"`v c #bfbfbf",
"`w c #0f0f0f",
"`x c #afafaf",
"`y c #3b3b3b",
"`z c #070707",
"`A c #7f7f7f",
"`B c #0b0b0b",
"`C c #272727",
"`D c #575757",
"`E c #6b6b6b",
"`F c #b3b3b3",
"`G c #f7f7f7",
"`H c #777777",
"`I c #5b5b5b",
"`J c #ababab",
"`K c #4f4f4f",
"`L c #838383",
"`M c #535353",
"`N c #cfcfcf",
"`O c #4b4b4b",
"`P c #878787",
"`Q c #131313",
"`R c #737373",
"`S c #1f1f1f",
"`T c #2f2f2f",
"`U c #8b8b8b",
"`V c #8f8f8f",
"`W c #d7d7d7",
"`X c #c7c7c7",
"`Y c #333333",
"`Z c #2b2b2b",
"`0 c #000000",
"`1 c #000000",
"`2 c #000000",
"`3 c #000000",
"`4 c #000000",
"`5 c #000000",
"`6 c #000000",
"`7 c #000000",
"`8 c #000000",
".` c #000000",
".. c #000000",
".# c #000000",
".a c #000000",
".b c #000000",
".c c #000000",
".d c #000000",
".e c #000000",
".f c #000000",
".g c #000000",
".h c #000000",
".i c #000000",
".j c #000000",
".k c #000000",
".l c #000000",
".m c #000000",
".n c #000000",
".o c #000000",
".p c #000000",
".q c #000000",
".r c #000000",
".s c #000000",
".t c #000000",
".u c #000000",
".v c #000000",
".w c #000000",
".x c #000000",
".y c #000000",
".z c #000000",
".A c #000000",
".B c #000000",
".C c #000000",
".D c #000000",
".E c #000000",
".F c #000000",
".G c #000000",
".H c #000000",
".I c #000000",
".J c #000000",
".K c #000000",
".L c #000000",
".M c #000000",
".N c #000000",
".O c #000000",
".P c #000000",
".Q c #000000",
".R c #000000",
".S c #000000",
".T c #000000",
".U c #000000",
".V c #000000",
".W c #000000",
".X c #000000",
".Y c #000000",
".Z c #000000",
".0 c #000000",
".1 c #000000",
".2 c #000000",
".3 c #000000",
".4 c #000000",
".5 c #000000",
".6 c #000000",
".7 c #000000",
".8 c #000000",
"#` c #000000",
"#. c #000000",
"## c #000000",
"#a c #000000",
"#b c #000000",
"#c c #000000",
"#d c #000000",
"#e c #000000",
"#f c #000000",
"#g c #000000",
"#h c #000000",
"#i c #000000",
"#j c #000000",
"#k c #000000",
"#l c #000000",
"#m c #000000",
"#n c #000000",
"#o c #000000",
"#p c #000000",
"#q c #000000",
"#r c #000000",
"#s c #000000",
"#t c #000000",
"#u c #000000",
"#v c #000000",
"#w c #000000",
"#x c #000000",
"#y c #000000",
"#z c #000000",
"#A c #000000",
"#B c #000000",
"#C c #000000",
"#D c #000000",
"#E c #000000",
"#F c #000000",
"#G c #000000",
"#H c #000000",
"#I c #000000",
"#J c #000000",
"#K c #000000",
"#L c #000000",
"#M c #000000",
"#N c #000000",
"#O c #000000",
"#P c #000000",
"#Q c #000000",
"#R c #000000",
"#S c #000000",
"#T c #000000",
"#U c #000000",
"#V c #000000",
"#W c #000000",
"#X c #000000",
"#Y c #000000",
"#Z c #000000",
"#0 c #000000",
"#1 c #000000",
"#2 c #000000",
"#3 c #000000",
"#4 c #000000",
"#5 c #000000",
"#6 c #000000",
"#7 c #000000",
"#8 c #000000",
"a` c #000000",
"a. c #000000",
"a# c #000000",
"aa c #000000",
"ab c #000000",
"ac c #000000",
"ad c #000000",
"ae c #000000",
"af c #000000",
"ag c #000000",
"ah c #000000",
"ai c #000000",
"aj c #000000",
"ak c #000000",
"al c #000000",
"am c #000000",
"an c #000000",
"ao c #000000",
"ap c #000000",
"aq c #000000",
"ar c #000000",
"as c #000000",
"at c #000000",
"au c #000000",
"av c #000000",
"aw c #000000",
"ax c #000000",
"ay c #000000",
"az c #000000",
"aA c #000000",
"aB c #000000",
"aC c #000000",
"aD c #000000",
"aE c #000000",
"aF c #000000",
"aG c #000000",
"aH c #000000",
"aI c #000000",
"aJ c #000000",
"aK c #000000",
"aL c #000000",
"aM c #000000",
"aN c #000000",
"aO c #000000",
"aP c #000000",
"aQ c #000000",
"aR c #000000",
"aS c #000000",
"aT c #000000",
"aU c #000000",
"aV c #000000",
"aW c #000000",
"aX c #000000",
"aY c #000000",
"aZ c #000000",
"a0 c #000000",
"a1 c #000000",
"a2 c #000000",
"a3 c #000000",
"a4 c #000000",
"a5 c #000000",
"a6 c #000000",
"a7 c #000000",
"a8 c #000000",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"```````````````````````````````````.`#`a`b`c`c`b`d`e`f``````````````````",
"```````````````````````````````g`h`i`j`j`j`j`j`j`j`j`k`l````````````````",
"`````````````````m`e`````````n`o`j`j`j`p`q`r`r`q`s`j`j`t`u``````````````",
"`````````````````v`p`````w`x`j`j`j`q`y```````````z`A`i`j`b`B````````````",
"```````````````m`j`v```C`p`j`j`t`D```````````````````E`j`j`h````````````",
"```````````````v`j`F`y`t`j`j`q`.```````````````````````d`j`i`l``````````",
"`````````````m`j`j`p`G`j`j`#```````````````````````````l`j`j`H``````````",
"`````````````v`j`j`j`j`i`I```````````````````````````````t`j`J``````````",
"```````````K`j`j`j`j`j`k`L`#`M`````````````````````````u`j`j`n``````````",
"```````````N`j`j`j`j`j`j`j`j`j`O```````````````````````P`j`i`Q``````````",
"`````````K`j`j`j`j`j`j`j`N`R`.```````````````````````S`c`j`x````````````",
"`````````N`j`j`j`j`N`#`l`````````````````````````````v`j`i`u````````````",
"```````K`j`j`p`L`T```````````````````````````````f`A`j`j`U``````````````",
"```````F`V`T```````````````````````````````````K`p`j`j`W`z``````````````",
"`````f```````````````````````````````````f`M`X`j`j`j`p`Y````````````````",
"`````````````````````````````````````````k`j`j`j`o`R`z``````````````````",
"`````````````````````````````````````````V`j`G`V`Q``````````````````````",
"`````````````````````````````````````````Z`R`w``````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````"
};
static Fl_Pixmap image_undo_black(idata_undo_black);

void CTabletToolbar::cb_btnSettings_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	
	CCalcSettings* calcSettings = new CCalcSettings();
	calcSettings->setView(view);
	calcSettings->centerWindow(mainWindow);
	calcSettings->show();
	delete calcSettings;
	view->setViewMode(CPaintView::VM_SKETCH);
};
}
void CTabletToolbar::cb_btnSettings(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnSettings_i(o,v);
}

static const char *idata_settings_black[] = {
"    36    36      256            2",
"`` c None",
"`. c #030303",
"`# c #4f4f4f",
"`a c #7f7f7f",
"`b c #434343",
"`c c #e7e7e7",
"`d c #fbfbfb",
"`e c #ffffff",
"`f c #f7f7f7",
"`g c #efefef",
"`h c #2f2f2f",
"`i c #dfdfdf",
"`j c #b3b3b3",
"`k c #c3c3c3",
"`l c #e3e3e3",
"`m c #5f5f5f",
"`n c #3f3f3f",
"`o c #bfbfbf",
"`p c #afafaf",
"`q c #ebebeb",
"`r c #f3f3f3",
"`s c #000000",
"`t c #000000",
"`u c #000000",
"`v c #000000",
"`w c #000000",
"`x c #000000",
"`y c #000000",
"`z c #000000",
"`A c #000000",
"`B c #000000",
"`C c #000000",
"`D c #000000",
"`E c #000000",
"`F c #000000",
"`G c #000000",
"`H c #000000",
"`I c #000000",
"`J c #000000",
"`K c #000000",
"`L c #000000",
"`M c #000000",
"`N c #000000",
"`O c #000000",
"`P c #000000",
"`Q c #000000",
"`R c #000000",
"`S c #000000",
"`T c #000000",
"`U c #000000",
"`V c #000000",
"`W c #000000",
"`X c #000000",
"`Y c #000000",
"`Z c #000000",
"`0 c #000000",
"`1 c #000000",
"`2 c #000000",
"`3 c #000000",
"`4 c #000000",
"`5 c #000000",
"`6 c #000000",
"`7 c #000000",
"`8 c #000000",
".` c #000000",
".. c #000000",
".# c #000000",
".a c #000000",
".b c #000000",
".c c #000000",
".d c #000000",
".e c #000000",
".f c #000000",
".g c #000000",
".h c #000000",
".i c #000000",
".j c #000000",
".k c #000000",
".l c #000000",
".m c #000000",
".n c #000000",
".o c #000000",
".p c #000000",
".q c #000000",
".r c #000000",
".s c #000000",
".t c #000000",
".u c #000000",
".v c #000000",
".w c #000000",
".x c #000000",
".y c #000000",
".z c #000000",
".A c #000000",
".B c #000000",
".C c #000000",
".D c #000000",
".E c #000000",
".F c #000000",
".G c #000000",
".H c #000000",
".I c #000000",
".J c #000000",
".K c #000000",
".L c #000000",
".M c #000000",
".N c #000000",
".O c #000000",
".P c #000000",
".Q c #000000",
".R c #000000",
".S c #000000",
".T c #000000",
".U c #000000",
".V c #000000",
".W c #000000",
".X c #000000",
".Y c #000000",
".Z c #000000",
".0 c #000000",
".1 c #000000",
".2 c #000000",
".3 c #000000",
".4 c #000000",
".5 c #000000",
".6 c #000000",
".7 c #000000",
".8 c #000000",
"#` c #000000",
"#. c #000000",
"## c #000000",
"#a c #000000",
"#b c #000000",
"#c c #000000",
"#d c #000000",
"#e c #000000",
"#f c #000000",
"#g c #000000",
"#h c #000000",
"#i c #000000",
"#j c #000000",
"#k c #000000",
"#l c #000000",
"#m c #000000",
"#n c #000000",
"#o c #000000",
"#p c #000000",
"#q c #000000",
"#r c #000000",
"#s c #000000",
"#t c #000000",
"#u c #000000",
"#v c #000000",
"#w c #000000",
"#x c #000000",
"#y c #000000",
"#z c #000000",
"#A c #000000",
"#B c #000000",
"#C c #000000",
"#D c #000000",
"#E c #000000",
"#F c #000000",
"#G c #000000",
"#H c #000000",
"#I c #000000",
"#J c #000000",
"#K c #000000",
"#L c #000000",
"#M c #000000",
"#N c #000000",
"#O c #000000",
"#P c #000000",
"#Q c #000000",
"#R c #000000",
"#S c #000000",
"#T c #000000",
"#U c #000000",
"#V c #000000",
"#W c #000000",
"#X c #000000",
"#Y c #000000",
"#Z c #000000",
"#0 c #000000",
"#1 c #000000",
"#2 c #000000",
"#3 c #000000",
"#4 c #000000",
"#5 c #000000",
"#6 c #000000",
"#7 c #000000",
"#8 c #000000",
"a` c #000000",
"a. c #000000",
"a# c #000000",
"aa c #000000",
"ab c #000000",
"ac c #000000",
"ad c #000000",
"ae c #000000",
"af c #000000",
"ag c #000000",
"ah c #000000",
"ai c #000000",
"aj c #000000",
"ak c #000000",
"al c #000000",
"am c #000000",
"an c #000000",
"ao c #000000",
"ap c #000000",
"aq c #000000",
"ar c #000000",
"as c #000000",
"at c #000000",
"au c #000000",
"av c #000000",
"aw c #000000",
"ax c #000000",
"ay c #000000",
"az c #000000",
"aA c #000000",
"aB c #000000",
"aC c #000000",
"aD c #000000",
"aE c #000000",
"aF c #000000",
"aG c #000000",
"aH c #000000",
"aI c #000000",
"aJ c #000000",
"aK c #000000",
"aL c #000000",
"aM c #000000",
"aN c #000000",
"aO c #000000",
"aP c #000000",
"aQ c #000000",
"aR c #000000",
"aS c #000000",
"aT c #000000",
"aU c #000000",
"aV c #000000",
"aW c #000000",
"aX c #000000",
"aY c #000000",
"aZ c #000000",
"a0 c #000000",
"a1 c #000000",
"a2 c #000000",
"a3 c #000000",
"a4 c #000000",
"a5 c #000000",
"a6 c #000000",
"a7 c #000000",
"a8 c #000000",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"```````````````````````.`#`a`a`a`a`a`a`a`a`a`a`a`b``````````````````````",
"```````````````````````#`c`d`e`e`e`e`e`e`e`e`e`f`g`h````````````````````",
"```````````````````````a`i`j`a`a`a`a`a`a`a`a`a`k`l`m````````````````````",
"```````````````````````a`i`m```````````````````a`i`m````````````````````",
"```````````````````````a`i`m```````````````````a`i`m````````````````````",
"```````````````````````a`i`m```````n`a`h```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`g`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`i`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`i`m```````a`i`m````````````````````",
"```````````````````````a`i`m```n`a`o`i`p`a`h```a`i`m````````````````````",
"```````````````````````a`i`m```a`g`e`g`e`g`m```a`i`m````````````````````",
"```````````````````````a`i`m```a`i`e`e`e`i`m```a`i`m````````````````````",
"```````````````````````a`i`m```a`g`e`g`e`g`m```a`i`m````````````````````",
"```````````````````````a`i`m```n`a`o`i`p`a`h```a`i`m````````````````````",
"```````````````````````a`i`m```````a`i`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`i`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`i`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`i`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`i`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`i`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`i`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`i`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````a`g`m```````a`i`m````````````````````",
"```````````````````````a`i`m```````n`a`h```````a`i`m````````````````````",
"```````````````````````a`i`m```````````````````a`i`m````````````````````",
"```````````````````````a`i`m```````````````````a`i`m````````````````````",
"```````````````````````a`i`j`a`a`a`a`a`a`a`a`a`k`l`m````````````````````",
"```````````````````````#`q`e`e`e`e`e`e`e`e`e`e`d`r`h````````````````````",
"```````````````````````.`#`a`a`a`a`a`a`a`a`a`a`a`b``````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````",
"````````````````````````````````````````````````````````````````````````"
};
static Fl_Pixmap image_settings_black(idata_settings_black);

void CTabletToolbar::cb_btnEx1_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->newModel();
};
}
void CTabletToolbar::cb_btnEx1(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnEx1_i(o,v);
}

void CTabletToolbar::cb_btnEx2_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->newModel();
};
}
void CTabletToolbar::cb_btnEx2(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnEx2_i(o,v);
}

void CTabletToolbar::cb_btnEx3_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->newModel();
};
}
void CTabletToolbar::cb_btnEx3(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnEx3_i(o,v);
}

void CTabletToolbar::cb_btnEx4_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->newModel();
};
}
void CTabletToolbar::cb_btnEx4(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnEx4_i(o,v);
}

void CTabletToolbar::cb_btnEx5_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->newModel();
};
}
void CTabletToolbar::cb_btnEx5(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnEx5_i(o,v);
}

void CTabletToolbar::cb_btnEx6_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->newModel();
};
}
void CTabletToolbar::cb_btnEx6(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnEx6_i(o,v);
}

void CTabletToolbar::cb_btnEx7_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->newModel();
};
}
void CTabletToolbar::cb_btnEx7(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnEx7_i(o,v);
}

void CTabletToolbar::cb_btnEx8_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->newModel();
};
}
void CTabletToolbar::cb_btnEx8(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnEx8_i(o,v);
}

void CTabletToolbar::cb_btnEx9_i(Fl_HoverButton*, void*) {
  if (m_paintView!=NULL)
{
	CPaintView* view = (CPaintView*)m_paintView;
	view->newModel();
};
}
void CTabletToolbar::cb_btnEx9(Fl_HoverButton* o, void* v) {
  ((CTabletToolbar*)(o->parent()->user_data()))->cb_btnEx9_i(o,v);
}

CTabletToolbar::CTabletToolbar() {
  { mainWindow = new Fl_Double_Window(258, 312, "Tablet Toolbar");
    mainWindow->color(FL_FOREGROUND_COLOR);
    mainWindow->user_data((void*)(this));
    { btnNew = new Fl_HoverButton(5, 3, 42, 42);
      btnNew->tooltip("New model");
      btnNew->box(FL_THIN_UP_BOX);
      btnNew->color(FL_FOREGROUND_COLOR);
      btnNew->selection_color(FL_BACKGROUND_COLOR);
      btnNew->image(image_new_model_black);
      btnNew->labeltype(FL_NORMAL_LABEL);
      btnNew->labelfont(0);
      btnNew->labelsize(14);
      btnNew->labelcolor(FL_FOREGROUND_COLOR);
      btnNew->callback((Fl_Callback*)cb_btnNew);
      btnNew->align(Fl_Align(FL_ALIGN_CENTER));
      btnNew->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnNew
    { btnUndo = new Fl_HoverButton(165, 3, 42, 42);
      btnUndo->tooltip("Undo");
      btnUndo->box(FL_THIN_UP_BOX);
      btnUndo->color(FL_FOREGROUND_COLOR);
      btnUndo->selection_color(FL_BACKGROUND_COLOR);
      btnUndo->image(image_undo_black);
      btnUndo->labeltype(FL_NORMAL_LABEL);
      btnUndo->labelfont(0);
      btnUndo->labelsize(14);
      btnUndo->labelcolor(FL_FOREGROUND_COLOR);
      btnUndo->callback((Fl_Callback*)cb_btnUndo);
      btnUndo->align(Fl_Align(FL_ALIGN_CENTER));
      btnUndo->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnUndo
    { btnSettings = new Fl_HoverButton(211, 3, 42, 42);
      btnSettings->tooltip("Calculation settings");
      btnSettings->box(FL_THIN_UP_BOX);
      btnSettings->color(FL_FOREGROUND_COLOR);
      btnSettings->selection_color(FL_BACKGROUND_COLOR);
      btnSettings->image(image_settings_black);
      btnSettings->labeltype(FL_NORMAL_LABEL);
      btnSettings->labelfont(0);
      btnSettings->labelsize(14);
      btnSettings->labelcolor(FL_FOREGROUND_COLOR);
      btnSettings->callback((Fl_Callback*)cb_btnSettings);
      btnSettings->align(Fl_Align(FL_ALIGN_CENTER));
      btnSettings->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnSettings
    { btnEx1 = new Fl_HoverButton(5, 58, 80, 80);
      btnEx1->tooltip("New model");
      btnEx1->box(FL_THIN_UP_BOX);
      btnEx1->color(FL_FOREGROUND_COLOR);
      btnEx1->selection_color(FL_BACKGROUND_COLOR);
      btnEx1->image(image_new_model_black);
      btnEx1->labeltype(FL_NORMAL_LABEL);
      btnEx1->labelfont(0);
      btnEx1->labelsize(14);
      btnEx1->labelcolor(FL_FOREGROUND_COLOR);
      btnEx1->callback((Fl_Callback*)cb_btnEx1);
      btnEx1->align(Fl_Align(FL_ALIGN_CENTER));
      btnEx1->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnEx1
    { btnEx2 = new Fl_HoverButton(89, 58, 80, 80);
      btnEx2->tooltip("New model");
      btnEx2->box(FL_THIN_UP_BOX);
      btnEx2->color(FL_FOREGROUND_COLOR);
      btnEx2->selection_color(FL_BACKGROUND_COLOR);
      btnEx2->image(image_new_model_black);
      btnEx2->labeltype(FL_NORMAL_LABEL);
      btnEx2->labelfont(0);
      btnEx2->labelsize(14);
      btnEx2->labelcolor(FL_FOREGROUND_COLOR);
      btnEx2->callback((Fl_Callback*)cb_btnEx2);
      btnEx2->align(Fl_Align(FL_ALIGN_CENTER));
      btnEx2->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnEx2
    { btnEx3 = new Fl_HoverButton(173, 58, 80, 80);
      btnEx3->tooltip("New model");
      btnEx3->box(FL_THIN_UP_BOX);
      btnEx3->color(FL_FOREGROUND_COLOR);
      btnEx3->selection_color(FL_BACKGROUND_COLOR);
      btnEx3->image(image_new_model_black);
      btnEx3->labeltype(FL_NORMAL_LABEL);
      btnEx3->labelfont(0);
      btnEx3->labelsize(14);
      btnEx3->labelcolor(FL_FOREGROUND_COLOR);
      btnEx3->callback((Fl_Callback*)cb_btnEx3);
      btnEx3->align(Fl_Align(FL_ALIGN_CENTER));
      btnEx3->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnEx3
    { btnEx4 = new Fl_HoverButton(5, 142, 80, 80);
      btnEx4->tooltip("New model");
      btnEx4->box(FL_THIN_UP_BOX);
      btnEx4->color(FL_FOREGROUND_COLOR);
      btnEx4->selection_color(FL_BACKGROUND_COLOR);
      btnEx4->image(image_new_model_black);
      btnEx4->labeltype(FL_NORMAL_LABEL);
      btnEx4->labelfont(0);
      btnEx4->labelsize(14);
      btnEx4->labelcolor(FL_FOREGROUND_COLOR);
      btnEx4->callback((Fl_Callback*)cb_btnEx4);
      btnEx4->align(Fl_Align(FL_ALIGN_CENTER));
      btnEx4->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnEx4
    { btnEx5 = new Fl_HoverButton(89, 142, 80, 80);
      btnEx5->tooltip("New model");
      btnEx5->box(FL_THIN_UP_BOX);
      btnEx5->color(FL_FOREGROUND_COLOR);
      btnEx5->selection_color(FL_BACKGROUND_COLOR);
      btnEx5->image(image_new_model_black);
      btnEx5->labeltype(FL_NORMAL_LABEL);
      btnEx5->labelfont(0);
      btnEx5->labelsize(14);
      btnEx5->labelcolor(FL_FOREGROUND_COLOR);
      btnEx5->callback((Fl_Callback*)cb_btnEx5);
      btnEx5->align(Fl_Align(FL_ALIGN_CENTER));
      btnEx5->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnEx5
    { btnEx6 = new Fl_HoverButton(173, 142, 80, 80);
      btnEx6->tooltip("New model");
      btnEx6->box(FL_THIN_UP_BOX);
      btnEx6->color(FL_FOREGROUND_COLOR);
      btnEx6->selection_color(FL_BACKGROUND_COLOR);
      btnEx6->image(image_new_model_black);
      btnEx6->labeltype(FL_NORMAL_LABEL);
      btnEx6->labelfont(0);
      btnEx6->labelsize(14);
      btnEx6->labelcolor(FL_FOREGROUND_COLOR);
      btnEx6->callback((Fl_Callback*)cb_btnEx6);
      btnEx6->align(Fl_Align(FL_ALIGN_CENTER));
      btnEx6->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnEx6
    { btnEx7 = new Fl_HoverButton(5, 226, 80, 80);
      btnEx7->tooltip("New model");
      btnEx7->box(FL_THIN_UP_BOX);
      btnEx7->color(FL_FOREGROUND_COLOR);
      btnEx7->selection_color(FL_BACKGROUND_COLOR);
      btnEx7->image(image_new_model_black);
      btnEx7->labeltype(FL_NORMAL_LABEL);
      btnEx7->labelfont(0);
      btnEx7->labelsize(14);
      btnEx7->labelcolor(FL_FOREGROUND_COLOR);
      btnEx7->callback((Fl_Callback*)cb_btnEx7);
      btnEx7->align(Fl_Align(FL_ALIGN_CENTER));
      btnEx7->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnEx7
    { btnEx8 = new Fl_HoverButton(89, 226, 80, 80);
      btnEx8->tooltip("New model");
      btnEx8->box(FL_THIN_UP_BOX);
      btnEx8->color(FL_FOREGROUND_COLOR);
      btnEx8->selection_color(FL_BACKGROUND_COLOR);
      btnEx8->image(image_new_model_black);
      btnEx8->labeltype(FL_NORMAL_LABEL);
      btnEx8->labelfont(0);
      btnEx8->labelsize(14);
      btnEx8->labelcolor(FL_FOREGROUND_COLOR);
      btnEx8->callback((Fl_Callback*)cb_btnEx8);
      btnEx8->align(Fl_Align(FL_ALIGN_CENTER));
      btnEx8->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnEx8
    { btnEx9 = new Fl_HoverButton(173, 226, 80, 80);
      btnEx9->tooltip("New model");
      btnEx9->box(FL_THIN_UP_BOX);
      btnEx9->color(FL_FOREGROUND_COLOR);
      btnEx9->selection_color(FL_BACKGROUND_COLOR);
      btnEx9->image(image_new_model_black);
      btnEx9->labeltype(FL_NORMAL_LABEL);
      btnEx9->labelfont(0);
      btnEx9->labelsize(14);
      btnEx9->labelcolor(FL_FOREGROUND_COLOR);
      btnEx9->callback((Fl_Callback*)cb_btnEx9);
      btnEx9->align(Fl_Align(FL_ALIGN_CENTER));
      btnEx9->when(FL_WHEN_RELEASE);
    } // Fl_HoverButton* btnEx9
    mainWindow->set_non_modal();
    mainWindow->end();
  } // Fl_Double_Window* mainWindow
  m_paintView = NULL;
}

void CTabletToolbar::show() {
  CPlatformInfoPtr platformInfo = CPlatformInfo::getInstance();
  
  mainWindow->show();
  
  
  #ifdef WIN32
  
  HWND handle = fl_xid(mainWindow);
  long oldStyle = GetWindowLongPtr(handle, GWL_EXSTYLE);
  SetWindowLongPtr(handle, GWL_EXSTYLE, oldStyle | WS_EX_TOOLWINDOW);
  
  #endif
}

void CTabletToolbar::setView(void* view) {
  m_paintView = view;
}

void CTabletToolbar::centerWindow(Fl_Window* window) {
  mainWindow->position(window->x()+window->w()/2-mainWindow->w()/2, window->y()+window->h()/2-mainWindow->h()/2);
}

void CTabletToolbar::placeWindow(Fl_Window* window) {
  mainWindow->position(window->x()+window->w()-mainWindow->w()-100, window->y()+window->h()-mainWindow->h()-100);
}

void CTabletToolbar::hide() {
  mainWindow->hide();
}
