// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef VizMixerToolbar_h
#define VizMixerToolbar_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Fl_HoverButton.h"
#include <FL/Fl_Box.H>
#include <FL/Fl_Wizard.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Check_Button.H>

class CVizMixerToolbar {
  void* m_paintView; 
public:
  CVizMixerToolbar();
  Fl_Double_Window *mainWindow;
  Fl_HoverButton *btnStress;
private:
  void cb_btnStress_i(Fl_HoverButton*, void*);
  static void cb_btnStress(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnDisplacements;
private:
  void cb_btnDisplacements_i(Fl_HoverButton*, void*);
  static void cb_btnDisplacements(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnMisesStress;
private:
  void cb_btnMisesStress_i(Fl_HoverButton*, void*);
  static void cb_btnMisesStress(Fl_HoverButton*, void*);
public:
  Fl_Wizard *wizard;
  Fl_Group *groupPrincipalStress;
  Fl_HoverButton *btnTensionCompression;
private:
  void cb_btnTensionCompression_i(Fl_HoverButton*, void*);
  static void cb_btnTensionCompression(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnTension;
private:
  void cb_btnTension_i(Fl_HoverButton*, void*);
  static void cb_btnTension(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnCompression;
private:
  void cb_btnCompression_i(Fl_HoverButton*, void*);
  static void cb_btnCompression(Fl_HoverButton*, void*);
public:
  Fl_Roller *rolArrowSize;
private:
  void cb_rolArrowSize_i(Fl_Roller*, void*);
  static void cb_rolArrowSize(Fl_Roller*, void*);
public:
  Fl_Roller *rolTransparency;
private:
  void cb_rolTransparency_i(Fl_Roller*, void*);
  static void cb_rolTransparency(Fl_Roller*, void*);
public:
  Fl_Roller *rolStep;
private:
  void cb_rolStep_i(Fl_Roller*, void*);
  static void cb_rolStep(Fl_Roller*, void*);
public:
  Fl_HoverButton *btnLockScale;
private:
  void cb_btnLockScale_i(Fl_HoverButton*, void*);
  static void cb_btnLockScale(Fl_HoverButton*, void*);
public:
  Fl_Slider *minStress;
private:
  void cb_minStress_i(Fl_Slider*, void*);
  static void cb_minStress(Fl_Slider*, void*);
public:
  Fl_Slider *maxStress;
private:
  void cb_maxStress_i(Fl_Slider*, void*);
  static void cb_maxStress(Fl_Slider*, void*);
public:
  Fl_Roller *maxIntensity;
private:
  void cb_maxIntensity_i(Fl_Roller*, void*);
  static void cb_maxIntensity(Fl_Roller*, void*);
public:
  Fl_Roller *stressWidth;
private:
  void cb_stressWidth_i(Fl_Roller*, void*);
  static void cb_stressWidth(Fl_Roller*, void*);
public:
  Fl_Group *groupMisesStress;
  Fl_HoverButton *btnColorMap1;
private:
  void cb_btnColorMap1_i(Fl_HoverButton*, void*);
  static void cb_btnColorMap1(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnColorMap2;
private:
  void cb_btnColorMap2_i(Fl_HoverButton*, void*);
  static void cb_btnColorMap2(Fl_HoverButton*, void*);
public:
  Fl_Slider *sldUpperMisesTreshold;
private:
  void cb_sldUpperMisesTreshold_i(Fl_Slider*, void*);
  static void cb_sldUpperMisesTreshold(Fl_Slider*, void*);
public:
  Fl_Check_Button *chkInvertColorMap;
private:
  void cb_chkInvertColorMap_i(Fl_Check_Button*, void*);
  static void cb_chkInvertColorMap(Fl_Check_Button*, void*);
public:
  Fl_Group *groupDisplacement;
  Fl_Slider *sldDisplacementScale;
private:
  void cb_sldDisplacementScale_i(Fl_Slider*, void*);
  static void cb_sldDisplacementScale(Fl_Slider*, void*);
public:
  Fl_HoverButton *btnMoveLoad;
private:
  void cb_btnMoveLoad_i(Fl_HoverButton*, void*);
  static void cb_btnMoveLoad(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnRotateLoad;
private:
  void cb_btnRotateLoad_i(Fl_HoverButton*, void*);
  static void cb_btnRotateLoad(Fl_HoverButton*, void*);
public:
  void show();
  void setView(void* view);
  void centerWindow(Fl_Window* window);
  void placeWindow(Fl_Window* window);
  void hide();
};
#endif
