// generated by Fast Light User Interface Designer (fluid) version 1.0105

#ifndef DrawingTools_h
#define DrawingTools_h
#include <FL/Fl.H>
#define MR_OK 0
#define MR_CANCEL 1
#include <FL/Fl_Double_Window.H>
#include "Fl_HoverButton.h"

class CDrawingTools {
  int m_modalResult;
  int m_currentTool;
  void* m_view;
public:
  CDrawingTools();
  Fl_Double_Window *wndBrushProps;
  Fl_HoverButton *btnOk;
private:
  inline void cb_btnOk_i(Fl_HoverButton*, void*);
  static void cb_btnOk(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnRectangle;
private:
  inline void cb_btnRectangle_i(Fl_HoverButton*, void*);
  static void cb_btnRectangle(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnEllipse;
private:
  inline void cb_btnEllipse_i(Fl_HoverButton*, void*);
  static void cb_btnEllipse(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnLine;
private:
  inline void cb_btnLine_i(Fl_HoverButton*, void*);
  static void cb_btnLine(Fl_HoverButton*, void*);
public:
  ~CDrawingTools();
  void show();
  void setPosition(int x, int y);
  void setSize(int width, int height);
  void setView(void* p);
  void hide();
};
#endif
