// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef BcTypes_h
#define BcTypes_h
#include <FL/Fl.H>
#define MR_OK 0
#define MR_CANCEL 1
/** New dialog class. */
#include <FL/Fl_Window.H>
#include "Fl_HoverButton.h"

class CBcTypes {
  int m_modalResult;
  int m_currentTool;
  void* m_view;
public:
  CBcTypes();
  Fl_Window *wnd;
  Fl_HoverButton *btnOk;
private:
  inline void cb_btnOk_i(Fl_HoverButton*, void*);
  static void cb_btnOk(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnBcX;
private:
  inline void cb_btnBcX_i(Fl_HoverButton*, void*);
  static void cb_btnBcX(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnBcY;
private:
  inline void cb_btnBcY_i(Fl_HoverButton*, void*);
  static void cb_btnBcY(Fl_HoverButton*, void*);
public:
  Fl_HoverButton *btnBcXY;
private:
  inline void cb_btnBcXY_i(Fl_HoverButton*, void*);
  static void cb_btnBcXY(Fl_HoverButton*, void*);
public:
  ~CBcTypes();
  void show();
  void setPosition(int x, int y);
  void setSize(int width, int height);
  void setView(void* p);
  void hide();
};
#endif
