// generated by Fast Light User Interface Designer (fluid) version 1.0105

#include "DrawingTools.h"
#include "PaintView.h"

inline void CDrawingTools::cb_btnOk_i(Fl_HoverButton*, void*) {
  m_modalResult = MR_OK;
wndBrushProps->hide();
}
void CDrawingTools::cb_btnOk(Fl_HoverButton* o, void* v) {
  ((CDrawingTools*)(o->parent()->user_data()))->cb_btnOk_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *idata_additional_close[] = {
"     5    36       18            1",
"` c #656565",
". c #696969",
"# c #797975",
"a c #797979",
"b c #7d7d7d",
"c c #81817d",
"d c #898989",
"e c #959191",
"f c #a19d9d",
"g c #aeaeaa",
"h c #b2aeaa",
"i c #bab6b2",
"j c #c6c6c2",
"k c #cecec6",
"l c #cececa",
"m c #d2ceca",
"n c #d2d2ca",
"o c None",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooolo",
"oomfl",
"ooibl",
"omd#l",
"oh.#l",
"kc`#l",
"h``#l",
"h``#l",
"kc`#l",
"og`#l",
"okc#l",
"oogal",
"ookel",
"ooojn",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo",
"ooooo"
};
static Fl_Pixmap image_additional_close(idata_additional_close);

inline void CDrawingTools::cb_btnRectangle_i(Fl_HoverButton*, void*) {
  if (m_view!=NULL)
{
	CPaintView* paintView = (CPaintView*) m_view;
	paintView->setEditMode(CPaintView::EM_RECTANGLE);
}
wndBrushProps->hide();
}
void CDrawingTools::cb_btnRectangle(Fl_HoverButton* o, void* v) {
  ((CDrawingTools*)(o->parent()->user_data()))->cb_btnRectangle_i(o,v);
}

static const char *idata_rectangle[] = {
"    36    36      105            2",
"`` c #7d6d4c",
"`. c #7d714c",
"`# c #896514",
"`a c #8d6914",
"`b c #916914",
"`c c #916d14",
"`d c #956d14",
"`e c #997114",
"`f c #9d7514",
"`g c #816934",
"`h c #816d38",
"`i c #856d38",
"`j c #a17914",
"`k c #a57914",
"`l c #aa7d18",
"`m c #81714c",
"`n c #8d7540",
"`o c #817150",
"`p c #857550",
"`q c #8d7d55",
"`r c #817965",
"`s c #817d79",
"`t c #817d7d",
"`u c #ae8118",
"`v c #b28518",
"`w c #b68518",
"`x c #b68918",
"`y c #ba8918",
"`z c #be8d18",
"`A c #be9118",
"`B c #998148",
"`C c #99855d",
"`D c #81817d",
"`E c #a5894c",
"`F c #b29555",
"`G c #b69955",
"`H c #ba9d55",
"`I c #a59569",
"`J c #bea155",
"`K c #b6a175",
"`L c #b6a57d",
"`M c #c29118",
"`N c #c6951c",
"`O c #ca991c",
"`P c #ce991c",
"`Q c #ce9d1c",
"`R c #d29d1c",
"`S c #d6a11c",
"`T c #daa51c",
"`U c #deaa20",
"`V c #e2ae20",
"`W c #e6ae20",
"`X c #e6b220",
"`Y c #eab220",
"`Z c #eeb620",
"`0 c #c2a155",
"`1 c #c2a159",
"`2 c #c2a559",
"`3 c #c6a559",
"`4 c #c6aa59",
"`5 c #caaa59",
"`6 c #ceae59",
"`7 c #d2b259",
"`8 c #d6b659",
".` c #dab659",
".. c #daba59",
".# c #deba5d",
".a c #debe5d",
".b c #e2be61",
".c c #858581",
".d c #898985",
".e c #8d8989",
".f c #8d8d89",
".g c #918d8d",
".h c #959591",
".i c #999591",
".j c #999995",
".k c #9d9995",
".l c #9d9d99",
".m c #a19d99",
".n c #a5a19d",
".o c #aaa5a1",
".p c #aaaaa5",
".q c #aeaaa5",
".r c #aeaeaa",
".s c #b2aeaa",
".t c #b2b2ae",
".u c #b6b2ae",
".v c #bab6b2",
".w c #babab6",
".x c #bebab6",
".y c #c2b695",
".z c #c2beba",
".A c #dec689",
".B c #c2c2ba",
".C c #c2c2be",
".D c #c6c2be",
".E c #c6c6be",
".F c #cac6c2",
".G c #cacac2",
".H c #cecac6",
".I c #cecec6",
".J c #d2ceca",
".K c #d2d2ca",
".L c None",
".L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L",
".L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L",
".L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L",
".L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L",
".L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L",
".L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L",
".L.L.L.L.L.L.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.L.L.L",
".L.L.L.L.K.K.J.I.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.I.J.K.K.L",
".L.L.L.K.A.b.b.a.#.#.#.#.#.#.#...``8`7`6`6`5`4`3`0`J`H`G`G`F`L.E.F.H.J.K",
".L.L.L.K.b`Z`Z`Z`Z`Z`Z`Z`Z`Z`Z`X`V`U`S`S`Q`O`N`A`z`x`v`l`k`j`E.v.z.F.H.K",
".L.L.K.J.b`Z`Z`Z`Z`Z`Z`Z`Z`Y`W`V`U`S`R`P`N`N`A`y`w`u`l`k`f`e`B.o.u.z.F.J",
".L.L.K.I.a`Z`Z`Z`Z`Z`Z`Z`Y`W`U`T`S`R`P`N`M`z`y`w`u`l`j`f`e`c`n.i.o.v.E.I",
".L.L.K.H.#`Z`Z`Z`Z`Z`Z`X`V`U`T`S`Q`O`N`M`z`x`v`l`l`j`f`d`b`a`i.e.m.u.C.H",
".L.L.K.H.#`Z`Z`Z`Z`Y`X`V`U`S`R`Q`O`N`A`y`x`v`l`k`f`e`d`b`#`#`g.c.j.s.z.H",
".L.L.K.H.#`Z`Z`Z`Y`W`U`U`S`R`P`N`M`A`y`w`u`l`k`f`e`c`a`#`#`#`g`D.i.r.z.H",
".L.L.K.H.#`Z`Z`X`W`U`T`S`Q`P`N`M`z`x`w`u`l`j`f`d`c`a`#`#`#`#`g`t.h.q.z.H",
".L.L.K.H.#`Z`X`V`U`T`S`Q`O`N`A`z`x`v`l`k`j`f`d`b`#`#`#`#`#`#`g`s.h.q.z.H",
".L.L.K.H.``W`V`U`S`R`P`O`N`A`y`w`v`l`k`f`e`c`b`#`#`#`#`#`#`#`g`s.h.q.z.H",
".L.L.K.H`8`U`T`S`R`P`N`M`z`y`w`u`l`j`f`e`c`a`#`#`#`#`#`#`#`#`g`s.h.q.z.H",
".L.L.K.H`7`T`S`Q`O`N`M`z`x`v`u`l`j`f`d`b`a`#`#`#`#`#`#`#`#`#`g`s.h.q.z.H",
".L.L.K.H`6`R`Q`O`N`A`y`x`v`l`k`f`f`d`b`#`#`#`#`#`#`#`#`#`#`#`g`s.h.q.z.H",
".L.L.K.H`5`P`N`N`A`y`w`u`l`k`f`e`c`a`#`#`#`#`#`#`#`#`#`#`#`#`g`s.h.q.z.H",
".L.L.K.H`4`N`M`z`x`w`u`l`j`f`e`c`a`#`#`#`#`#`#`#`#`#`#`#`#`#`g`D.h.q.z.H",
".L.L.K.H`2`M`z`x`v`l`k`j`f`d`b`#`#`#`#`#`#`#`#`#`#`#`#`#`#`#`g`D.i.r.z.H",
".L.L.K.H`1`y`w`v`l`k`f`e`d`b`#`#`#`#`#`#`#`#`#`#`#`#`#`#`#`#`h.c.j.s.z.H",
".L.L.K.H.y`K`I`C`q`p`m`.```````````````````````````````````o`r.f.m.u.D.H",
".L.L.K.I.F.w.p.k.g.d.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.d.g.k.p.w.F.I",
".L.L.L.J.G.B.v.q.n.m.l.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.l.m.n.q.v.B.G.J",
".L.L.L.K.I.F.C.x.v.u.u.u.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.u.u.u.v.x.C.F.I.K",
".L.L.L.L.K.I.H.F.E.D.D.D.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.D.D.D.E.F.H.I.K.L",
".L.L.L.L.L.K.J.J.I.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.I.J.J.K.L.L",
".L.L.L.L.L.L.L.L.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.L.L.L.L.L",
".L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L",
".L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L",
".L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L",
".L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L"
};
static Fl_Pixmap image_rectangle(idata_rectangle);

inline void CDrawingTools::cb_btnEllipse_i(Fl_HoverButton*, void*) {
  if (m_view!=NULL)
{
	CPaintView* paintView = (CPaintView*) m_view;
	paintView->setEditMode(CPaintView::EM_ELLIPSE);
}
wndBrushProps->hide();
}
void CDrawingTools::cb_btnEllipse(Fl_HoverButton* o, void* v) {
  ((CDrawingTools*)(o->parent()->user_data()))->cb_btnEllipse_i(o,v);
}

static const char *idata_ellipse[] = {
"    36    36      182            2",
"`` c #796538",
"`. c #79653c",
"`# c #7d693c",
"`a c #756948",
"`b c #796944",
"`c c #7d6d4c",
"`d c #756950",
"`e c #7d714c",
"`f c #797159",
"`g c #7d7159",
"`h c #716d65",
"`i c #756d61",
"`j c #757165",
"`k c #71716d",
"`l c #797165",
"`m c #797569",
"`n c #79756d",
"`o c #757571",
"`p c #797571",
"`q c #797575",
"`r c #797975",
"`s c #7d7975",
"`t c #7d7979",
"`u c #7d7d79",
"`v c #856518",
"`w c #85651c",
"`x c #896514",
"`y c #8d6514",
"`z c #896518",
"`A c #916914",
"`B c #956d14",
"`C c #95711c",
"`D c #997114",
"`E c #997518",
"`F c #816524",
"`G c #856520",
"`H c #856524",
"`I c #81652c",
"`J c #896920",
"`K c #896924",
"`L c #896d30",
"`M c #916d24",
"`N c #a17914",
"`O c #a17918",
"`P c #a57d18",
"`Q c #816d44",
"`R c #817148",
"`S c #8d7540",
"`T c #817150",
"`U c #897950",
"`V c #817961",
"`W c #857961",
"`X c #aa8118",
"`Y c #b28518",
"`Z c #b68918",
"`0 c #ba8d18",
"`1 c #be8d18",
"`2 c #be8d1c",
"`3 c #aa852c",
"`4 c #ae892c",
"`5 c #b2913c",
"`6 c #9d8548",
"`7 c #99855d",
"`8 c #81817d",
".` c #898171",
".. c #898579",
".# c #958561",
".a c #958d75",
".b c #958d7d",
".c c #a18540",
".d c #b29544",
".e c #b69d5d",
".f c #baa169",
".g c #c2911c",
".h c #ca991c",
".i c #ce9d1c",
".j c #c29524",
".k c #c69928",
".l c #d2a11c",
".m c #d6a11c",
".n c #daa51c",
".o c #cea12c",
".p c #d6a524",
".q c #d6aa28",
".r c #deaa20",
".s c #d2a538",
".t c #e2ae20",
".u c #eab220",
".v c #eeb620",
".w c #eeb624",
".x c #eeb628",
".y c #eaba2c",
".z c #e6ba3c",
".A c #eaba38",
".B c #c6a144",
".C c #caaa55",
".D c #daba5d",
".E c #daba69",
".F c #dabe6d",
".G c #d2ba75",
".H c #dabe75",
".I c #e6ba44",
".J c #e2be55",
".K c #e2be61",
".L c #898581",
".M c #898585",
".N c #898985",
".O c #8d8985",
".P c #8d8989",
".Q c #8d8d89",
".R c #918d85",
".S c #918d89",
".T c #918d8d",
".U c #95918d",
".V c #959191",
".W c #959591",
".X c #999591",
".Y c #999995",
".Z c #9d9995",
".0 c #9d9d95",
".1 c #9d9d99",
".2 c #a19d99",
".3 c #aaa189",
".4 c #aea589",
".5 c #a1a19d",
".6 c #a5a19d",
".7 c #aaa191",
".8 c #b2a591",
"#` c #a5a5a1",
"#. c #aaa5a1",
"## c #aaaaa5",
"#a c #aeaaa5",
"#b c #aeaeaa",
"#c c #b2aeaa",
"#d c #b6b2a5",
"#e c #b2b2ae",
"#f c #b6b2ae",
"#g c #b6b6ae",
"#h c #bab6aa",
"#i c #b6b6b2",
"#j c #bab6b2",
"#k c #babab2",
"#l c #babab6",
"#m c #bebab6",
"#n c #bebeb6",
"#o c #bebeba",
"#p c #c2b289",
"#q c #ceba81",
"#r c #ceba89",
"#s c #c2b295",
"#t c #cabe99",
"#u c #c6beaa",
"#v c #cabea1",
"#w c #c2beb6",
"#x c #c2beba",
"#y c #d6c285",
"#z c #d6c28d",
"#A c #dac285",
"#B c #dac691",
"#C c #dac699",
"#D c #c6c2b6",
"#E c #c2c2ba",
"#F c #c2c2be",
"#G c #c6c2ba",
"#H c #c6c2be",
"#I c #c6c6be",
"#J c #cac6be",
"#K c #d2c6a1",
"#L c #d2c6a5",
"#M c #d2caae",
"#N c #d6cab2",
"#O c #d6cab6",
"#P c #d2caba",
"#Q c #cac6c2",
"#R c #cacac2",
"#S c #cecac6",
"#T c #cecec6",
"#U c #d2cec2",
"#V c #d2cec6",
"#W c #d2ceca",
"#X c #d2d2ca",
"#Y c None",
"#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#X#X#X#X#X#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#X#W#W#W#T#S#S#S#T#W#W#X#X#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#X#U#M#K#y.H.D.G#q#t#u#G#Q#S#T#W#X#Y#Y#Y#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#Y#X#U#A.I.y.x.v.u.t.r.n.p.o.B#p#w#H#R#S#W#X#Y#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#X#N.K.w.v.v.v.u.t.r.n.m.l.i.h.j.e#d#o#I#S#W#X#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#X#B.z.v.v.v.v.u.t.r.n.m.l.i.h.g`1`0`5.4#j#F#R#W#X#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#X#C.y.v.v.v.v.u.t.r.n.m.l.i.h.g`1`0`Z`Y`3.7#i#x#R#W#X#Y#Y#Y#Y",
"#Y#Y#Y#Y#X#O.I.v.v.v.v.u.t.r.n.m.l.i.h.g`1`0`Z`Y`X`P`6.6#f#E#S#W#X#Y#Y#Y",
"#Y#Y#Y#Y#V.K.v.v.v.v.u.t.r.n.m.l.i.h.g`1`0`Z`Y`X`P`N`E.##.#j#H#S#X#Y#Y#Y",
"#Y#Y#Y#X#B.x.v.v.v.u.t.r.n.m.l.i.h.g`1`0`Z`Y`X`P`N`D`B`M.b#a#m#Q#T#X#Y#Y",
"#Y#Y#Y#V.J.v.v.v.u.t.r.n.m.l.i.h.g`1`0`Z`Y`X`P`N`D`B`A`y`U.2#c#x#S#W#Y#Y",
"#Y#Y#X#P.A.v.v.u.t.r.n.m.l.i.h.g`1`0`Z`Y`X`P`N`D`B`A`y`x`L.U#.#l#Q#W#X#Y",
"#Y#Y#X#L.x.v.u.t.r.n.m.l.i.h.g`1`0`Z`Y`X`P`N`D`B`A`y`x`x`J...2#f#F#S#X#Y",
"#Y#Y#W#z.v.u.t.r.n.m.l.i.h.g`1`0`Z`Y`X`P`N`D`B`A`y`x`x`x`x`W.W#a#o#R#W#Y",
"#Y#X#W.F.u.t.r.n.m.l.i.h.g`1`0`Z`Y`X`P`N`D`B`A`y`x`x`x`x`x`R.S#.#l#Q#W#Y",
"#Y#X#T.E.t.r.n.m.l.i.h.g`1`0`Z`Y`X`P`N`D`B`A`y`x`x`x`x`x`x`Q.O.6#j#I#W#X",
"#Y#X#S#r.r.n.m.l.i.h.g`1`0`Z`Y`X`P`N`D`B`A`y`x`x`x`x`x`x`x`g.N.2#i#H#T#X",
"#Y#X#S#v.q.m.l.i.h.g`1`0`Z`Y`X`P`N`D`B`A`y`x`x`x`x`x`x`x`w`m.N.2#i#H#T#X",
"#Y#X#T#D.s.l.i.h.g`1`0`Z`Y`X`P`N`D`B`A`y`x`x`x`x`x`x`x`x`I`p.O.6#j#I#W#X",
"#Y#X#W#J.C.i.h.g`1`0`Z`Y`X`P`N`D`B`A`y`x`x`x`x`x`x`x`x`x`b`t.T#.#l#Q#W#Y",
"#Y#Y#W#Q#s.k.g`1`0`Z`Y`X`P`N`D`B`A`y`x`x`x`x`x`x`x`x`x`F`j`8.X#a#o#S#W#Y",
"#Y#Y#X#S#x.f`2`0`Z`Y`X`P`N`D`B`A`y`x`x`x`x`x`x`x`x`x`v`d`q.N.2#f#H#S#X#Y",
"#Y#Y#X#T#I#h.d`Z`Y`X`P`N`D`B`A`y`x`x`x`x`x`x`x`x`x`x`.`k`8.V###m#Q#W#X#Y",
"#Y#Y#Y#W#R#x.8`4`X`P`N`D`B`A`y`x`x`x`x`x`x`x`x`x`x`I`h`u.Q.5#f#F#S#X#Y#Y",
"#Y#Y#Y#X#T#Q#l.3.c`O`D`B`A`y`x`x`x`x`x`x`x`x`x`z```h`r.N.Z#b#n#Q#W#X#Y#Y",
"#Y#Y#Y#Y#W#S#H#i.6`7`C`A`y`x`x`x`x`x`x`x`x`x`G`a`k`t.N.Y###l#I#S#X#Y#Y#Y",
"#Y#Y#Y#Y#X#W#R#E#f#`.a`S`K`z`x`x`x`x`x`w`H`#`i`o`8.P.Z###j#H#S#W#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#X#W#R#E#i##.0.R.``V`T`e`c`f`l`n`s`8.N.U.2#a#j#H#S#W#X#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#X#W#R#H#l#c#`.Z.U.Q.N.M.L.M.O.S.W.1#.#e#m#H#S#W#X#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#X#W#S#Q#x#j#c###`.5.2.2.2.5#`#a#f#l#E#Q#S#W#X#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#Y#X#W#T#S#I#E#n#k#j#f#f#g#j#l#o#F#Q#S#W#X#Y#Y#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#X#W#T#S#R#Q#I#H#H#H#I#Q#R#S#W#W#X#Y#Y#Y#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#X#X#W#W#W#T#T#T#W#W#W#X#X#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#X#X#X#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y",
"#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y#Y"
};
static Fl_Pixmap image_ellipse(idata_ellipse);

inline void CDrawingTools::cb_btnLine_i(Fl_HoverButton*, void*) {
  if (m_view!=NULL)
{
	CPaintView* paintView = (CPaintView*) m_view;
	paintView->setEditMode(CPaintView::EM_LINE);
}
wndBrushProps->hide();
}
void CDrawingTools::cb_btnLine(Fl_HoverButton* o, void* v) {
  ((CDrawingTools*)(o->parent()->user_data()))->cb_btnLine_i(o,v);
}

static const char *idata_line[] = {
"    36    36      125            2",
"`` c #79715d",
"`. c #7d7159",
"`# c #75716d",
"`a c #797165",
"`b c #79756d",
"`c c #797575",
"`d c #797975",
"`e c #7d7975",
"`f c #7d7979",
"`g c #7d7d79",
"`h c #997114",
"`i c #9d7514",
"`j c #8d712c",
"`k c #8d7134",
"`l c #8d7538",
"`m c #8d753c",
"`n c #917120",
"`o c #91712c",
"`p c #91752c",
"`q c #a17914",
"`r c #a57d14",
"`s c #a17918",
"`t c #a57d18",
"`u c #a57d1c",
"`v c #aa7d18",
"`w c #8d7950",
"`x c #8d7d50",
"`y c #857961",
"`z c #817d79",
"`A c #aa8118",
"`B c #ae8118",
"`C c #b28518",
"`D c #b68918",
"`E c #b6891c",
"`F c #ba8d18",
"`G c #ba8d1c",
"`H c #be8d18",
"`I c #be8d1c",
"`J c #ae8528",
"`K c #b68920",
"`L c #ba8d20",
"`M c #9d8548",
"`N c #958559",
"`O c #81817d",
"`P c #85817d",
"`Q c #ae8d40",
"`R c #ba994c",
"`S c #a59569",
"`T c #baaa79",
"`U c #c29118",
"`V c #c2911c",
"`W c #c29530",
"`X c #c69d30",
"`Y c #c69d34",
"`Z c #ca9d30",
"`0 c #c29d44",
"`1 c #c6a144",
"`2 c #caa548",
"`3 c #c6a559",
"`4 c #c2a561",
"`5 c #c6a561",
"`6 c #c6aa61",
"`7 c #c6aa69",
"`8 c #c6b27d",
".` c #858181",
".. c #858581",
".# c #898581",
".a c #898585",
".b c #898985",
".c c #8d8985",
".d c #8d8989",
".e c #8d8d89",
".f c #91918d",
".g c #95918d",
".h c #99958d",
".i c #959191",
".j c #959591",
".k c #999591",
".l c #999995",
".m c #9d9995",
".n c #9d9d99",
".o c #a19d99",
".p c #a1a19d",
".q c #a5a19d",
".r c #aea599",
".s c #bab29d",
".t c #a5a5a1",
".u c #aaa5a1",
".v c #aaaaa5",
".w c #aeaaa5",
".x c #aeaeaa",
".y c #b2aeaa",
".z c #b2b2ae",
".A c #b6b2ae",
".B c #b6b6b2",
".C c #bab6b2",
".D c #babab6",
".E c #bebab6",
".F c #bebeb6",
".G c #bebeba",
".H c #c6b689",
".I c #cebe99",
".J c #cebe9d",
".K c #c2baa5",
".L c #c2beba",
".M c #cec29d",
".N c #d2c29d",
".O c #cec2aa",
".P c #c2c2ba",
".Q c #c2c2be",
".R c #c6c2be",
".S c #c6c6be",
".T c #cec6b2",
".U c #cecabe",
".V c #cac6c2",
".W c #cacac2",
".X c #cecac2",
".Y c #cecac6",
".Z c #cecec6",
".0 c #d2cac2",
".1 c #d2cec6",
".2 c #d6cec2",
".3 c #d2ceca",
".4 c #d2d2ca",
".5 c None",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.2.5.5.5.5.5.5.5.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.4.N`2.J.3.4.4.5.5.5.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.4.M`Z`V`W.H.X.3.4.5.5.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.4.I`X`V`H`F`K`T.V.Z.4.5.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.4.O`Y`U`H`D`C`B`J.s.V.Z.4.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.4.T`1`U`H`D`C`B`u`S.A.P.Y.3.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.4.T`1`U`H`D`C`B`u`N.l.w.E.V.3.4.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.4.T`1`H`F`D`C`B`u`w...i.u.C.V.Z.4.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.4.T`1`H`F`D`C`A`t`m`e...k.v.E.V.3.4.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.4.T`1`H`F`D`C`A`t`m`b`z.e.o.y.L.Y.3.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.4.T`0`H`F`D`C`A`t`m`b`g.b.m.w.E.V.Z.4.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.4.T`0`H`D`C`B`v`t`m`#`f.b.l.v.C.R.Y.3.5.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.4.U`3`H`D`C`B`v`s`l`#`f.a.k.u.C.R.Y.3.4.5.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.4.U`6`I`D`C`B`v`s`l`#`f.a.k.u.C.Q.Y.3.4.5.5.5.5.5",
".5.5.5.5.5.5.5.5.5.5.4.U`4`G`D`C`B`v`s`l`#`e.a.k.u.C.Q.Y.3.4.5.5.5.5.5.5",
".5.5.5.5.5.5.5.5.5.4.0`5`G`D`C`A`r`q`k`#`e.#.k.u.C.Q.Y.3.4.5.5.5.5.5.5.5",
".5.5.5.5.5.5.5.5.4.0`5`G`D`C`A`r`q`o`a`e.#.k.u.C.Q.Y.3.4.5.5.5.5.5.5.5.5",
".5.5.5.5.5.5.5.4.0`4`E`D`C`A`r`q`o`a`d...j.u.B.Q.Y.3.4.5.5.5.5.5.5.5.5.5",
".5.5.5.5.5.5.4.0`4`E`C`B`v`q`i`p`a`d...j.t.B.P.W.3.4.5.5.5.5.5.5.5.5.5.5",
".5.5.5.5.5.4.1`7`E`C`B`v`q`i`o`a`d...g.q.A.P.W.3.4.5.5.5.5.5.5.5.5.5.5.5",
".5.5.5.5.4.3`8`L`C`B`v`q`i`o`a`d...g.q.A.L.W.3.4.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.5.4.3`8`K`C`A`r`q`i`o`a`d.`.g.q.A.L.V.3.4.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.5.3`8`K`C`A`r`q`i`j`a`d.`.g.q.A.L.V.3.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.4.U`R`C`A`r`q`i`n```d.`.g.q.A.L.V.Z.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.3.Y.K`Q`t`q`i`n`.`c`P.f.q.A.L.V.Z.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.3.V.G.r`M`h`n`.`d`O.f.q.A.L.V.Z.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.3.V.F.w.h`x`y`g...f.p.y.G.V.Z.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.3.W.L.y.p.g.c.d.i.p.y.G.V.Z.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.4.Y.S.D.x.q.n.o.u.A.G.V.Z.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.4.3.Y.R.E.A.y.z.C.L.V.Z.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.5.4.3.Y.V.Q.L.P.R.W.Z.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.5.5.4.3.Z.Y.Y.Y.Y.3.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.5.5.5.5.4.4.4.4.4.4.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5",
".5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5"
};
static Fl_Pixmap image_line(idata_line);

CDrawingTools::CDrawingTools() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = wndBrushProps = new Fl_Double_Window(143, 103, "Brush properties");
    w = o;
    o->box(FL_THIN_UP_BOX);
    o->user_data((void*)(this));
    { Fl_HoverButton* o = btnOk = new Fl_HoverButton(132, 3, 9, 42);
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->image(image_additional_close);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(12);
      o->labelcolor(FL_BLACK);
      o->callback((Fl_Callback*)cb_btnOk);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    { Fl_HoverButton* o = btnRectangle = new Fl_HoverButton(3, 3, 42, 42);
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->image(image_rectangle);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->callback((Fl_Callback*)cb_btnRectangle);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    { Fl_HoverButton* o = btnEllipse = new Fl_HoverButton(46, 3, 42, 42);
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->image(image_ellipse);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->callback((Fl_Callback*)cb_btnEllipse);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    { Fl_HoverButton* o = btnLine = new Fl_HoverButton(89, 3, 42, 42);
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->image(image_line);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->callback((Fl_Callback*)cb_btnLine);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    o->set_non_modal();
    o->clear_border();
    o->end();
  }
  m_view = NULL;
}

CDrawingTools::~CDrawingTools() {
  delete wndBrushProps;
}

void CDrawingTools::show() {
  setSize(wndBrushProps->w(),btnOk->h()+4);

wndBrushProps->show();
//while (wndBrushProps->visible()) Fl::wait();
}

void CDrawingTools::setPosition(int x, int y) {
  wndBrushProps->position(x, y);
}

void CDrawingTools::setSize(int width, int height) {
  wndBrushProps->size_range(0, 0);
wndBrushProps->size(width, height);
}

void CDrawingTools::setView(void* p) {
  m_view = p;
}

void CDrawingTools::hide() {
  wndBrushProps->hide();
}
