// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef DrawingProps_h
#define DrawingProps_h
#include <FL/Fl.H>
#define MR_OK 0
#define MR_CANCEL 1
#include <FL/Fl_Double_Window.H>
#include "Fl_HoverButton.h"
#include <FL/Fl_Value_Slider.H>

class CDrawingProps {
  void* m_view; 
  int m_modalResult; 
public:
  CDrawingProps();
  Fl_Double_Window *wndDrawingProps;
  Fl_HoverButton *btnOk;
private:
  void cb_btnOk_i(Fl_HoverButton*, void*);
  static void cb_btnOk(Fl_HoverButton*, void*);
public:
  Fl_Value_Slider *sldBlendFactor;
private:
  void cb_sldBlendFactor_i(Fl_Value_Slider*, void*);
  static void cb_sldBlendFactor(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *sldLineWidth;
private:
  void cb_sldLineWidth_i(Fl_Value_Slider*, void*);
  static void cb_sldLineWidth(Fl_Value_Slider*, void*);
public:
  ~CDrawingProps();
  void show();
  void setPosition(int x, int y);
  void setSize(int width, int height);
  void setView(void* p);
  void hide();
};
#endif
