// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "LogWindow.h"
#include <iostream>
#include <string>

LogWindow* LogWindow::m_instance = 0; 

LogWindow::LogWindow() {
}

void LogWindow::hide() {
}

void LogWindow::show() {
}

LogWindow* LogWindow::getInstance() {
  if(m_instance==0)
{
	m_instance = new LogWindow();
        return m_instance;
}
else
{
	return m_instance;
}
}

void LogWindow::print(const std::string& txt) {
  using namespace std;
cout << txt << endl;
}

void LogWindow::print(const std::string &context, const std::string &txt) {
  using namespace std;
cout << context << ": " << txt << endl;
}
