// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef LogWindow_h
#define LogWindow_h
#include <FL/Fl.H>
#ifdef WIN32
#include "editlog_stream.h"
#endif
#include "so_format.h"
#define so_show() LogWindow::getInstance()->show();
#define so_print(a,b) LogWindow::getInstance()->print(a,b);
#define so_println() LogWindow::getInstance()->print("");
#define so_hide() LogWindow::getInstance()->hide();
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Display.H>

#include <iostream>
#include <string>

class LogWindow {
#ifdef WIN32
  std::basic_streambuf<char>* m_oldBuf; 
  std::basic_editstreambuf<char> m_editStrBuf; 
#endif
  static LogWindow* m_instance; 
  LogWindow();
public:
  Fl_Double_Window *mainWindow;
  Fl_Text_Display *textDisplay;
  void hide();
  void show();
  static LogWindow* getInstance();
  void print(const std::string& txt);
  void print(const std::string& context, const std::string& txt);
};
#endif
