// generated by Fast Light User Interface Designer (fluid) version 1.0101

#ifndef StatusDlg_h
#define StatusDlg_h
#include <FL/Fl.H>
/** Status window class */
#include <FL/Fl_Window.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Output.H>

class CStatusDlg {
/** Status window class constrcutor. */
public:
  CStatusDlg();
  Fl_Window *wndStatus;
  Fl_Value_Slider *sldProgress;
  Fl_Output *outStatus;
/** StatusDlg class constructor. */
  ~CStatusDlg();
/** Show window. */
  void show();
/** Set status text. */
  void setStatusText(const char* text);
/** Set progress value in percent. */
  void setProgress(int percent);
/** Hide window. */
  void hide();
/** Refresh window */
  void refresh();
};
#endif
